name: Machine Learning Workflow CI

on:
  push:
    branches: [ main ]

jobs:
  run-ml-pipeline:
    runs-on: ubuntu-latest

    steps:
    # 1. Menyiapkan job & Menjalankan actions/checkout
    - name: Checkout Repository
      uses: actions/checkout@v3

    # 2. Menyiapkan lingkungan Python
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    # 3. Memeriksa info environment
    - name: Check Environment Info
      run: |
        python --version
        pip --version

    # 4. Menginstal dependensi library
    - name: Install MLflow & Core Dependencies
      run: |
        pip install pandas numpy scikit-learn mlflow joblib

    # 5. Menjalankan fungsi training ulang lewat MLflow Project
    - name: Run MLflow Project (Re-training)
      run: |
        mlflow run MLProject --env-manager local

    # 6. Mengunggah berkas model biner (.pkl) ke GitHub Artifacts
    - name: Upload Trained Model Artifact to GitHub
      uses: actions/upload-artifact@v4
      with:
        name: trained-model-artifact
        path: MLProject/outputs/model.pkl